version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restaurant_choose
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
  web:
    build: .
    command: bash -c "./reset_models.sh && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db