# Generated by Django 3.2.4 on 2021-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='food_item/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodmanus',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='restaurant/'),
        ),
    ]
